{{- if not .Values.existingImagePullSecret }}
{{- if .Values.customImagePullSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.customImagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "customImagePullSecret" . }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: orkesregistry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}