{{- $ingresses := dict -}}
{{- if .Values.ingress.enabled -}}
  {{- $_ := set $ingresses "default" .Values.ingress -}}
{{- end -}}
{{- if .Values.extraIngresses -}}
  {{- range $name, $config := .Values.extraIngresses -}}
    {{- if $config.enabled -}}
      {{- $_ := set $ingresses $name $config -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- range $name, $config := $ingresses -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ if eq $name "default" }}{{ $.Release.Name }}-ingress{{ else }}{{ $.Release.Name }}-{{ $name }}{{ end }}
  labels:
    app.kubernetes.io/name: orkes-conductor
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: app
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $config.className }}
  ingressClassName: {{ $config.className }}
  {{- end }}
  {{- if $config.tls }}
  tls:
    {{- range $config.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $config.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- else }}
            pathType: Prefix
            {{- end }}
            backend:
              service:
                name: {{ $.Release.Name }}-server
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end -}}
