{{- $ingresses := dict -}}
{{- if .Values.ingress.enabled -}}
  {{- $_ := set $ingresses "default" .Values.ingress -}}
{{- end -}}
{{- if .Values.extraIngresses -}}
  {{- range $name, $config := .Values.extraIngresses -}}
    {{- if $config.enabled -}}
      {{- $_ := set $ingresses $name $config -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- $uiServiceName := default "conductor" .Values.conductor.uiServiceName -}}
{{- $apiServiceName := default "conductor-app" .Values.conductor.appServiceName -}}

{{- range $name, $config := $ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ if eq $name "default" }}{{ $.Release.Name }}-ingress{{ else }}{{ $.Release.Name }}-{{ $name }}{{ end }}
  labels:
    app.kubernetes.io/name: orkes-conductor
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: app
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
{{- if $config.annotations }}
  annotations:
{{ toYaml $config.annotations | nindent 4 }}
{{- end }}
spec:
{{- if $config.className }}
  ingressClassName: {{ $config.className }}
{{- end }}
{{- if $config.tls }}
  tls:
{{ toYaml $config.tls | nindent 4 }}
{{- end }}
  rules:
{{- range $config.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{- range .paths }}
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ if or (hasPrefix "/api" .path) (hasPrefix "/swagger-ui" .path) (hasPrefix "/api-docs" .path) (hasPrefix "/v3/api-docs" .path) }}{{ $apiServiceName }}{{ else }}{{ $uiServiceName }}{{ end }}
                port:
                  number: {{ .port }}
{{- end }}
{{- end }}
{{- end }}
