# SEE: https://github.com/helm/chart-testing-action
name: Lint and Test Charts

on: pull_request

env:
  CONFIG_FILE: ct.yaml

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.10.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config "${CONFIG_FILE}" --target-branch ${{ github.event.repository.default_branch }} --charts charts/orkes-conductor

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Set up Docker secret
        run: |
          kubectl create namespace chart-testing || true
          kubectl create secret docker-registry orkes-registry \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_HUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_HUB_TOKEN }} \
            --docker-email=${{ secrets.DOCKER_HUB_EMAIL }} \
            --namespace=chart-testing
        if: steps.list-changed.outputs.changed == 'true'

      - name: Add Bitnami Helm repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install Redis
        run: |
          helm install orkes-conductor-redis bitnami/redis \
            --namespace chart-testing \
            --set architecture=standalone \
            --set auth.enabled=false \
            --set master.resources.requests.memory=256Mi \
            --set master.resources.requests.cpu=200m \
            --set master.persistence.enabled=false \
            --wait --timeout 5m
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install PostgreSQL
        run: |
          helm install orkes-conductor-postgres bitnami/postgresql \
            --namespace chart-testing \
            --set auth.username=postgres \
            --set auth.password=postgres \
            --set primary.resources.requests.memory=256Mi \
            --set primary.resources.requests.cpu=200m \
            --set primary.persistence.enabled=false \
            --wait --timeout 5m
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config "${CONFIG_FILE}" --namespace chart-testing --helm-extra-set-args="--set-file=conductor.properties=examples/Evaluation/conductor.properties.test --set-file=workers.properties=examples/Evaluation/workers.properties.test" --charts charts/orkes-conductor
        if: steps.list-changed.outputs.changed == 'true'